/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package on3;

import entity.SinhVien;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel dcbm;
    private DefaultTableModel dtm;
    List<SinhVien> listSinhVien = new ArrayList<>();
    ButtonGroup buttonGroup = new ButtonGroup();

    public Main() {
        initComponents();
        rdGioiTinh();
        addItemComboBox();
        addItemColumns();
        addRow();
    }

    private void rdGioiTinh() {
        buttonGroup.add(rd_nam);
        buttonGroup.add(rd_nu);
    }

    private List<SinhVien> getList() {
        return listSinhVien;
    }

    private void addItemComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        dcbm = (DefaultComboBoxModel) cb_namsinh.getModel();
        listItem.add("1990");
        listItem.add("1991");
        listItem.add("1992");
        listItem.add("1993");
        listItem.add("1994");
        listItem.add("1995");
        listItem.add("1996");
        listItem.add("1997");
        listItem.add("1998");
        listItem.add("1999");
        listItem.add("2000");
        listItem.add("2001");
        listItem.add("2002");
        listItem.add("2003");

        for (String item : listItem) {
            dcbm.addElement(item);
        }
    }

    private void addItemColumns() {
        List<String> listItems = new ArrayList<>();
        listItems.add("Tên sinh viên");
        listItems.add("Giới tính");
        listItems.add("Tuổi");
        listItems.add("Địa chỉ");
        dtm = (DefaultTableModel) tb_sinhvien.getModel();
        dtm.setColumnCount(0);
        for (String listItem : listItems) {
            dtm.addColumn(listItem);
        }
    }

    private void addRow() {
        List<SinhVien> list = getList();
        dtm = (DefaultTableModel) tb_sinhvien.getModel();
        dtm.setRowCount(0);
        for (SinhVien x : list) {
            dtm.addRow(
                    new Object[] {
                            x.getHoTen(),
                            x.getGioiTinh(),
                            x.getNam(),
                            x.getDiaChi()
                    });
        }
    }

    private void ghiFile() throws IOException {
        File file = new File("file.txt");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

        FileOutputStream fos = new FileOutputStream(file);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        for (SinhVien x : listSinhVien) {
            oos.writeObject(x);
        }

        oos.close();
        fos.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_hoten = new javax.swing.JLabel();
        lbl_namsinh = new javax.swing.JLabel();
        lbl_gioitinh = new javax.swing.JLabel();
        lbl_diachi = new javax.swing.JLabel();
        txt_hoten = new javax.swing.JTextField();
        cb_namsinh = new javax.swing.JComboBox<>();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        txt_diachi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sinhvien = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_load = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Quản lý sinh viên");

        lbl_hoten.setText("Họ tên sinh viên");

        lbl_namsinh.setText("Năm sinh");

        lbl_gioitinh.setText("Giới tính");

        lbl_diachi.setText("Địa chỉ");

        rd_nam.setText("Nam");

        rd_nu.setText("Nữ");

        tb_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        tb_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sinhvien);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_load.setText("LoadData");
        btn_load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadActionPerformed(evt);
            }
        });

        btn_ghi.setText("Ghi file");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(266, 266, 266)
                                                .addComponent(jLabel1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lbl_hoten)
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                false)
                                                                                .addComponent(lbl_gioitinh,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(lbl_namsinh,
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        62, Short.MAX_VALUE))
                                                                        .addComponent(lbl_diachi,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                48,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(90, 90, 90)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txt_hoten,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                163,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txt_diachi,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                165,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cb_namsinh,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(rd_nam,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        98,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(rd_nu,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        98,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addGap(52, 52, 52)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btn_load)
                                                                        .addComponent(btn_xoa)
                                                                        .addComponent(btn_ghi)
                                                                        .addComponent(btn_them)))
                                                        .addComponent(jScrollPane1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 587,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(109, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbl_hoten)
                                                        .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn_them))
                                                .addGap(37, 37, 37)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbl_namsinh)
                                                        .addComponent(cb_namsinh,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btn_xoa))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lbl_gioitinh)
                                                        .addComponent(rd_nam)
                                                        .addComponent(rd_nu)
                                                        .addComponent(btn_load))
                                                .addGap(46, 46, 46)
                                                .addComponent(btn_ghi))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lbl_diachi)
                                                .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(77, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (txt_hoten.getText().equals("") || txt_diachi.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống.");
        } else {
            List<SinhVien> list = getList();
            SinhVien sv = new SinhVien();
            String hoTen = txt_hoten.getText();
            String diaChi = txt_diachi.getText();

            if (rd_nam.isSelected()) {
                sv.setGioiTinh("Nam");
            } else {
                sv.setGioiTinh("Nữ");
            }
            int namSinh = Integer.parseInt(cb_namsinh.getSelectedItem().toString());

            sv.setHoTen(hoTen);
            sv.setNam(2022 - namSinh);
            sv.setDiaChi(diaChi);

            listSinhVien.add(sv);

            JOptionPane.showMessageDialog(this, "Thêm thành công.");

        }
    }// GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int remove = tb_sinhvien.getSelectedRow();
        if (remove == -1) {
            JOptionPane.showMessageDialog(this, "Chọn 1 dòng để xóa.");
        } else {
            int opt = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa", "yes", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {
                listSinhVien.remove(opt);
            }
        }
    }// GEN-LAST:event_btn_xoaActionPerformed

    private void btn_loadActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_loadActionPerformed
        // TODO add your handling code here:
        addRow();
    }// GEN-LAST:event_btn_loadActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        SinhVien sv = new SinhVien();
        sv.setHoTen(txt_hoten.getText());
        sv.setDiaChi(txt_diachi.getText());
        if (rd_nam.isSelected()) {
            sv.setGioiTinh("Nam");
        } else {
            sv.setGioiTinh("Nữ");
        }
        int namSinh = Integer.parseInt(cb_namsinh.getSelectedItem().toString());
        cb_namsinh.setSelectedItem(namSinh);
        listSinhVien.add(sv);
        try {
            ghiFile();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }// GEN-LAST:event_btn_ghiActionPerformed

    private void tb_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tb_sinhvienMouseClicked
        // TODO add your handling code here:
        int row = tb_sinhvien.getSelectedRow();
        txt_hoten.setText(tb_sinhvien.getValueAt(row, 0).toString());
        txt_diachi.setText(tb_sinhvien.getValueAt(row, 3).toString());
        cb_namsinh.setSelectedItem(tb_sinhvien.getValueAt(row, 2));
        if (tb_sinhvien.getValueAt(row, 1).toString().equals("Nam")) {
            rd_nam.setSelected(true);
        } else {
            rd_nu.setSelected(true);
        }

    }// GEN-LAST:event_tb_sinhvienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_load;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_namsinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_diachi;
    private javax.swing.JLabel lbl_gioitinh;
    private javax.swing.JLabel lbl_hoten;
    private javax.swing.JLabel lbl_namsinh;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTable tb_sinhvien;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_hoten;
    // End of variables declaration//GEN-END:variables
}
