/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.SinhVien;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.ISinhVienService;
import service.SinhVienService;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel dcbm;
    private DefaultTableModel dtm;
    ISinhVienService<SinhVien> sinhVienIService = new SinhVienService<>();
    private SinhVien t;

    public Main() {
        initComponents();
        addComboBox();
        addColumns();
        addRow();
    }

    private void addComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("UDPM");
        listItem.add("WEB");

        dcbm = (DefaultComboBoxModel) cb_mon.getModel();
        for (String item : listItem) {
            dcbm.addElement(item);
        }
    }

    private void addColumns() {
        ArrayList<String> listItems = new ArrayList<>();
        listItems.add("Tên sinh viên");
        listItems.add("Môn");
        listItems.add("Trạng thái");

        dtm = (DefaultTableModel) tb_sinhvien.getModel();
        dtm.setColumnCount(0);
        for (String items : listItems) {
            dtm.addColumn(items);
        }
    }

    private void addRow() {
        dtm = (DefaultTableModel) tb_sinhvien.getModel();
        dtm.setRowCount(0);
        for (SinhVien x : sinhVienIService.getList()) {
            dtm.addRow(
                    new Object[]{
                        x.getTen(),
                        x.getMon(),
                        x.getTrangThai()
                    });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tensv = new javax.swing.JLabel();
        lbl_mon = new javax.swing.JLabel();
        txt_tensv = new javax.swing.JTextField();
        cb_mon = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sinhvien = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_mo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tensv.setText("Tên sinh viên");

        lbl_mon.setText("Môn");

        tb_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null },
                        { null, null, null },
                        { null, null, null },
                        { null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3"
                }));
        tb_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sinhvien);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_ghi.setText("Ghi file");

        btn_mo.setText("Mở file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_tensv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(lbl_mon, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(98, 98, 98)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt_tensv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cb_mon, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(173, 173, 173)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(btn_xoa)
                                                        .addComponent(btn_them)
                                                        .addComponent(btn_ghi)
                                                        .addComponent(btn_mo))))
                                .addContainerGap(187, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_tensv)
                                        .addComponent(txt_tensv, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_them))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_xoa)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbl_mon)
                                        .addComponent(cb_mon, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn_ghi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_mo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54,
                                        Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (txt_tensv.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "No title");
        } else {
            SinhVien sv = new SinhVien();
            String tenSV = txt_tensv.getText();
            Object boMon = cb_mon.getSelectedItem().toString();

            sv.setTen(tenSV);
            sv.setMon((String) boMon);
            sv.setTrangThai("Active");

            sinhVienIService.add(sv);
            addRow();
            JOptionPane.showMessageDialog(this, "Them thanh cong");

        }
    }// GEN-LAST:event_btn_themActionPerformed

    private void tb_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tb_sinhvienMouseClicked
        // TODO add your handling code here:
        int row = tb_sinhvien.getSelectedRow();
        txt_tensv.setText(tb_sinhvien.getValueAt(row, 0).toString());
        cb_mon.setSelectedItem(tb_sinhvien.getValueAt(row, 1));
    }// GEN-LAST:event_tb_sinhvienMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        SinhVien sv = new SinhVien();
        boolean check = sinhVienIService.remove(t);
        if(check == true){
            
        }
        addRow();
    }// GEN-LAST:event_btn_xoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_mo;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_mon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_mon;
    private javax.swing.JLabel lbl_tensv;
    private javax.swing.JTable tb_sinhvien;
    private javax.swing.JTextField txt_tensv;
    // End of variables declaration//GEN-END:variables
}
