/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package toantu;

import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_soa = new javax.swing.JLabel();
        lbl_sob = new javax.swing.JLabel();
        txt_soa = new javax.swing.JTextField();
        txt_sob = new javax.swing.JTextField();
        btn_cong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_ketqua = new javax.swing.JTextField();
        btn_tru = new javax.swing.JButton();
        btn_tich = new javax.swing.JButton();
        btn_thuong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_soa.setText("Số a");

        lbl_sob.setText("Số b");

        btn_cong.setText("Cộng");
        btn_cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_congActionPerformed(evt);
            }
        });

        jLabel1.setText("Kết quả");

        btn_tru.setText("Trừ");
        btn_tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_truActionPerformed(evt);
            }
        });

        btn_tich.setText("Nhân ");
        btn_tich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tichActionPerformed(evt);
            }
        });

        btn_thuong.setText("Chia");
        btn_thuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thuongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_sob, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_sob, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbl_soa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(txt_soa, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(245, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cong)
                        .addGap(43, 43, 43)
                        .addComponent(btn_tru)
                        .addGap(38, 38, 38)
                        .addComponent(btn_tich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_thuong)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_soa)
                    .addComponent(txt_soa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sob)
                    .addComponent(txt_sob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_ketqua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cong)
                    .addComponent(btn_tru)
                    .addComponent(btn_tich)
                    .addComponent(btn_thuong))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_congActionPerformed
        // TODO add your handling code here:
        if(txt_soa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if(txt_sob.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else{
            try {
                double a = Double.parseDouble(txt_soa.getText());
                double b = Double.parseDouble(txt_sob.getText());
                double tong = a + b;
                txt_ketqua.setText(String.valueOf(tong));
            } catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Phai nhap so");
            }
        }
    }//GEN-LAST:event_btn_congActionPerformed

    private void btn_truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_truActionPerformed
        // TODO add your handling code here:
        if(txt_soa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if(txt_sob.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else{
            try {
                double a = Double.parseDouble(txt_soa.getText());
                double b = Double.parseDouble(txt_sob.getText());
                double hieu = a - b;
                txt_ketqua.setText(String.valueOf(hieu));
            } catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Phai nhap so");
            }
        }
    }//GEN-LAST:event_btn_truActionPerformed

    private void btn_tichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tichActionPerformed
        // TODO add your handling code here:
        if(txt_soa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if(txt_sob.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else{
            try {
                double a = Double.parseDouble(txt_soa.getText());
                double b = Double.parseDouble(txt_sob.getText());
                double tich = a * b;
                txt_ketqua.setText(String.valueOf(tich));
            } catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Phai nhap so");
            }
        }
    }//GEN-LAST:event_btn_tichActionPerformed

    private void btn_thuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thuongActionPerformed
        // TODO add your handling code here:
        if(txt_soa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if(txt_sob.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else{
            try {
                double a = Double.parseDouble(txt_soa.getText());
                double b = Double.parseDouble(txt_sob.getText());
                double thuong = a / b;
                txt_ketqua.setText(String.valueOf(thuong));
            } catch(NumberFormatException nfe) {
                JOptionPane.showMessageDialog(this, "Phai nhap so");
            } catch (ArithmeticException ae) {
                JOptionPane.showMessageDialog(this, "Mẫu khác không");
            }
        }
    }//GEN-LAST:event_btn_thuongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cong;
    private javax.swing.JButton btn_thuong;
    private javax.swing.JButton btn_tich;
    private javax.swing.JButton btn_tru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_soa;
    private javax.swing.JLabel lbl_sob;
    private javax.swing.JTextField txt_ketqua;
    private javax.swing.JTextField txt_soa;
    private javax.swing.JTextField txt_sob;
    // End of variables declaration//GEN-END:variables
}
