/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onc;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel defaultComboBoxModel;
    private DefaultTableModel defaultTableModel;
    List<HoaDon> listHoaDon = new ArrayList<>();

    public Main() {
        initComponents();
        addComboBox();
        addColumns();
        Thread t = new Thread(this);
        t.start();
    }

    public void addComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("Trẻ em");
        listItem.add("Người lớn");

        defaultComboBoxModel = (DefaultComboBoxModel) cb_loaive.getModel();
        for (String item : listItem) {
            defaultComboBoxModel.addElement(item);
        }
    }

    public void addColumns() {
        ArrayList<String> list = new ArrayList<>();
        list.add("Tên Khách Hàng");
        list.add("Loại vé");
        list.add("Số lượng");
        list.add("Thành tiền");

        defaultTableModel = (DefaultTableModel) tb_hoadon.getModel();
        defaultTableModel.setColumnCount(0);
        for (String items : list) {
            defaultTableModel.addColumn(items);
        }
    }

    public void addRow() {
        defaultTableModel = (DefaultTableModel) tb_hoadon.getModel();
        defaultTableModel.setRowCount(0);

        for (HoaDon x : listHoaDon) {
            defaultTableModel.addRow(
                    new Object[]{
                        x.getTenKH(),
                        x.getLoaiVe(),
                        x.getSoLuong(),
                        x.getThanhTien()
                    }
            );
        }
    }

    public void ghiFile() throws FileNotFoundException, IOException {
        File file = new File("khanh.txt");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        FileOutputStream fos = new FileOutputStream(file);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        for (HoaDon hoaDon : listHoaDon) {
            oos.writeObject(hoaDon);
        }
        oos.close();
        fos.close();
    }

    public ArrayList<HoaDon> moFile() throws FileNotFoundException, IOException, ClassNotFoundException {
        File file = new File("khanh.txt");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        FileInputStream fis = new FileInputStream(file);
        ObjectInputStream ois = new ObjectInputStream(fis);

        HoaDon hoaDon = new HoaDon();
        ArrayList<HoaDon> list = new ArrayList<>();
        while (fis.available() > 0) {
            hoaDon = (HoaDon) ois.readObject();
            list.add(hoaDon);
        }
        System.out.println(list.size());

        ois.close();
        fis.close();

        return list;
    }

    public HoaDon timTheoTen(String ten) {
        for (HoaDon hoaDon : listHoaDon) {
            if (hoaDon.getTenKH().equalsIgnoreCase(ten)) {
                return hoaDon;
            }
        }
        return null;
    }

    public void fill(HoaDon hd) {
        txt_tenkh.setText(hd.getTenKH());
        cb_loaive.setSelectedItem(hd.getLoaiVe());
        txt_soluong.setText(String.valueOf(hd.getSoLuong()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tenkh = new javax.swing.JLabel();
        lbl_loaive = new javax.swing.JLabel();
        lbl_soluong = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        cb_loaive = new javax.swing.JComboBox<>();
        txt_soluong = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_mo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_hoadon = new javax.swing.JTable();
        lbl_time = new javax.swing.JTextField();
        btn_tim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tenkh.setText("Tên Khách Hàng");

        lbl_loaive.setText("Loại vé");

        lbl_soluong.setText("Số Lượng");

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_ghi.setText("Ghi File");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        btn_mo.setText("Mở File");
        btn_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moActionPerformed(evt);
            }
        });

        tb_hoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_hoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_hoadon);

        btn_tim.setText("Find");
        btn_tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbl_tenkh)
                                            .addGap(24, 24, 24))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lbl_loaive, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(61, 61, 61)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_soluong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_tenkh, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(cb_loaive, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_soluong))))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_them)
                                .addComponent(btn_xoa)
                                .addComponent(btn_mo)
                                .addComponent(btn_ghi))
                            .addComponent(btn_tim))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tenkh)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_loaive)
                            .addComponent(cb_loaive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_xoa)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_soluong)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btn_ghi)
                        .addGap(27, 27, 27)
                        .addComponent(btn_mo)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_hoadonMouseClicked
        // TODO add your handling code here:
        int row = tb_hoadon.getSelectedRow();
        txt_soluong.setText(tb_hoadon.getValueAt(row, 0).toString());
        cb_loaive.setSelectedItem(tb_hoadon.getValueAt(row, 1));
        txt_soluong.setText(tb_hoadon.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tb_hoadonMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (txt_tenkh.getText().equals("") || txt_soluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else if (Integer.parseInt(txt_soluong.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "nhập số lượng lỗi");
        } else {
            HoaDon hd = new HoaDon();
            String tenKH = txt_tenkh.getText();
            Object loaiVe = cb_loaive.getSelectedItem();
            int soLuong = Integer.parseInt(txt_soluong.getText());
            int thanhTien;
            if (cb_loaive.getSelectedItem().equals("Trẻ em")) {
                thanhTien = soLuong * 80000;
            } else {
                thanhTien = soLuong * 100000;
            }

            hd.setTenKH(tenKH);
            hd.setLoaiVe((String) loaiVe);
            hd.setSoLuong(soLuong);
            hd.setThanhTien(thanhTien);
            listHoaDon.add(hd);

            addRow();
            JOptionPane.showMessageDialog(this, "thêm thành công");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int row = tb_hoadon.getSelectedRow();
        listHoaDon.remove(row);
        addRow();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        try {
            // TODO add your handling code here:
            ghiFile();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moActionPerformed
        try {
            ArrayList<HoaDon> listHoaDon = moFile();
            defaultTableModel = (DefaultTableModel) tb_hoadon.getModel();
            defaultTableModel.setRowCount(0);
            for (HoaDon x : listHoaDon) {
                defaultTableModel.addRow(
                        new Object[]{
                            x.getTenKH(),
                            x.getLoaiVe(),
                            x.getSoLuong(),
                            x.getThanhTien()
                        }
                );
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_moActionPerformed

    private void btn_timActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timActionPerformed
        // TODO add your handling code here:
        fill(timTheoTen(txt_tenkh.getText()));
    }//GEN-LAST:event_btn_timActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_mo;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_tim;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_loaive;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_loaive;
    private javax.swing.JLabel lbl_soluong;
    private javax.swing.JLabel lbl_tenkh;
    private javax.swing.JTextField lbl_time;
    private javax.swing.JTable tb_hoadon;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tenkh;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            Calendar c = Calendar.getInstance();

            int h = c.get(Calendar.HOUR_OF_DAY);
            int p = c.get(Calendar.MINUTE);

            SimpleDateFormat sdf = new SimpleDateFormat("hh:mm aa");
            Date date = c.getTime();

            String time = sdf.format(date);

            lbl_time.setText(time);
        }
    }
}
