/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi5;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel defaultComboBoxModel;
    private DefaultTableModel defaultTableModel;

    private List<Sach> listSach = new ArrayList<>();

    ButtonGroup buttonGroup;

    public Main() {
        initComponents();
        rdTheLoai();
        addItemComboBox();
        addItemColumns();

        Sach s1 = new Sach("Sach 1", "Nguyen Van A", 1, 2010);
        Sach s2 = new Sach("Sach 2", "Tran Thi B", 1, 2013);
        Sach s3 = new Sach("Sach 3", "Le Dinh C", 2, 2017);

        listSach.add(s1);
        listSach.add(s2);
        listSach.add(s3);

        addRow();

    }

    void rdTheLoai() {
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rd_tieu);
        buttonGroup.add(rd_truyen);
    }

    public List<Sach> getList() {
        return listSach;
    }

    public void addRow() {
        List<Sach> list = getList();
        defaultTableModel = (DefaultTableModel) tb_sach.getModel();
        defaultTableModel.setRowCount(0);
        for (Sach sach : list) {
            defaultTableModel.addRow(
                    new Object[]{
                        sach.getTenSach(), sach.getTacGia(), getTenTheLoai(sach.getTheLoai()), sach.getNamIn()
                    }
            );
        }
    }
    
    public String getTenTheLoai(int theLoai) {
        if (theLoai == 1) {
            return "Truyện ngắn";
        } else if (theLoai == 2) {
            return "Tiểu thuyết";
        } else {
            return null;
        }
    }

    public void addItemComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("2010");
        listItem.add("2011");
        listItem.add("2012");
        listItem.add("2013");
        listItem.add("2014");
        listItem.add("2015");
        listItem.add("2016");
        listItem.add("2017");
        listItem.add("2018");
        listItem.add("2019");
        listItem.add("2020");

        defaultComboBoxModel = (DefaultComboBoxModel) cb_namin.getModel();

        for (String item : listItem) {
            defaultComboBoxModel.addElement(item);
        }

        cb_namin.setSelectedIndex(5);
    }

    public void addItemColumns() {
        ArrayList<String> listItemt = new ArrayList<>();
        listItemt.add("Tên Sách");
        listItemt.add("Tác Giả");
        listItemt.add("Thể Loại");
        listItemt.add("Năm In");

        defaultTableModel = (DefaultTableModel) tb_sach.getModel();
        defaultTableModel.setColumnCount(0);
        for (String item1 : listItemt) {
            defaultTableModel.addColumn(item1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tensach = new javax.swing.JLabel();
        lbl_tacgia = new javax.swing.JLabel();
        lbl_theloai = new javax.swing.JLabel();
        lbl_namin = new javax.swing.JLabel();
        txt_tensach = new javax.swing.JTextField();
        txt_tacgia = new javax.swing.JTextField();
        rd_truyen = new javax.swing.JRadioButton();
        rd_tieu = new javax.swing.JRadioButton();
        cb_namin = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sach = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tensach.setText("Tên Sách");

        lbl_tacgia.setText("Tác Giả");

        lbl_theloai.setText("Thể Loại");

        lbl_namin.setText("Năm in");

        rd_truyen.setText("Truyện Ngắn");

        rd_tieu.setText("Tiểu Thuyết");

        tb_sach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_sach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sach);

        btn_them.setText("Them");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 688, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_theloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_tensach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_tacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(lbl_namin))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_namin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_tensach, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                        .addComponent(txt_tacgia))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rd_truyen, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rd_tieu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_clear)
                                    .addComponent(btn_them)
                                    .addComponent(btn_xoa))))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tensach)
                    .addComponent(txt_tensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tacgia)
                    .addComponent(txt_tacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_theloai)
                    .addComponent(rd_truyen)
                    .addComponent(rd_tieu)
                    .addComponent(btn_clear))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_namin)
                    .addComponent(cb_namin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_tacgia.setText("");
        txt_tensach.setText("");
        buttonGroup.clearSelection();
        cb_namin.setSelectedIndex(5);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int remove = tb_sach.getSelectedRow();
        if (remove == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng để xóa");
        } else {
            int opt = JOptionPane.showConfirmDialog(null, "Ban co muon xoa", "xoa", JOptionPane.YES_NO_OPTION);
            if (opt == 0) {
                int row = tb_sach.getSelectedRow();
                listSach.remove(row);
                addRow();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        List<Sach> list = getList();
        Sach sach = new Sach();
        String tenSach = txt_tensach.getText();
        String tacGia = txt_tacgia.getText();
        int namIn;
        namIn = Integer.parseInt((String) cb_namin.getSelectedItem());
        if (rd_truyen.isSelected()) {
            sach.setTheLoai(1);
        } else if (rd_tieu.isSelected()) {
            sach.setTheLoai(2);
        }

        sach.setTenSach(tenSach);
        sach.setTacGia(tacGia);
        sach.setNamIn(namIn);

        listSach.add(sach);
        addRow();
    }//GEN-LAST:event_btn_themActionPerformed

    private void tb_sachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sachMouseClicked
        // TODO add your handling code here:
        int row = tb_sach.getSelectedRow();
        txt_tensach.setText((String) tb_sach.getValueAt(row, 0));
        txt_tacgia.setText((String) tb_sach.getValueAt(row, 1));
        cb_namin.setSelectedItem(tb_sach.getValueAt(row, 3).toString());
        String theLoai = tb_sach.getValueAt(row, 2).toString();
        if (tb_sach.getValueAt(row, 2).toString().equals("Tiểu thuyết")) {
            rd_tieu.setSelected(true);
        } else {
            rd_truyen.setSelected(true);
        }
    }//GEN-LAST:event_tb_sachMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_namin;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_namin;
    private javax.swing.JLabel lbl_tacgia;
    private javax.swing.JLabel lbl_tensach;
    private javax.swing.JLabel lbl_theloai;
    private javax.swing.JRadioButton rd_tieu;
    private javax.swing.JRadioButton rd_truyen;
    private javax.swing.JTable tb_sach;
    private javax.swing.JTextField txt_tacgia;
    private javax.swing.JTextField txt_tensach;
    // End of variables declaration//GEN-END:variables
}
