/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package on;

import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel defaultComboBoxModel;
    private DefaultTableModel defaultTableModel;
    List<Phong> listPhong = new ArrayList<>();

    ButtonGroup buttonGroup = new ButtonGroup();

    public Main() {
        initComponents();
        rdTinhTrang();
        addItemComboBox();
        addItemColumns();
    }

    public void rdTinhTrang() {
        buttonGroup.add(rd_chuathue);
        buttonGroup.add(rd_dathue);
    }

    public List<Phong> getList() {
        return listPhong;
    }

    public void addRow() {
        List<Phong> list = getList();
        defaultTableModel = (DefaultTableModel) tb_table.getModel();
        defaultTableModel.setRowCount(0);
        for (Phong phong : list) {
            defaultTableModel.addRow(
                    new Object[]{
                        phong.getSoPhong(),
                        phong.getDiaChi(),
                        phong.getNguoiThue(),
                        getTheTinhTrang(phong.getTinhTrang()),
                        phong.getSoNguoi()
                    }
            );
        }
    }

    public void addItemComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("1");
        listItem.add("2");
        listItem.add("3");
        listItem.add("4");

        defaultComboBoxModel = (DefaultComboBoxModel) cb_songuoi.getModel();

        for (String item : listItem) {
            defaultComboBoxModel.addElement(item);
        }

        cb_songuoi.setSelectedIndex(0);
    }

    public void addItemColumns() {
        ArrayList<String> listItems = new ArrayList<>();
        listItems.add("Số Phòng");
        listItems.add("Địa Chỉ");
        listItems.add("Người Thuê");
        listItems.add("Tình Trạng");
        listItems.add("Số Người");

        defaultTableModel = (DefaultTableModel) tb_table.getModel();
        defaultTableModel.setColumnCount(0);
        for (String listItem : listItems) {
            defaultTableModel.addColumn(listItem);
        }
    }

    public String getTheTinhTrang(int tinhTrang) {
        if (tinhTrang == 1) {
            return "Chưa thuê";
        } else if (tinhTrang == 0) {
            return "Thuê";
        } else {
            return "null";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_sophong = new javax.swing.JLabel();
        lbl_diachi = new javax.swing.JLabel();
        lbl_nguoithue = new javax.swing.JLabel();
        lbl_tinhtrang = new javax.swing.JLabel();
        lbl_songuoi = new javax.swing.JLabel();
        txt_sophong = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_nguoithue = new javax.swing.JTextField();
        rd_chuathue = new javax.swing.JRadioButton();
        rd_dathue = new javax.swing.JRadioButton();
        cb_songuoi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_table = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_sophong.setText("Số Phòng");

        lbl_diachi.setText("Địa Chỉ");

        lbl_nguoithue.setText("Người Thuê");

        lbl_tinhtrang.setText("Tình Trạng");

        lbl_songuoi.setText("Số Người");

        rd_chuathue.setText("Chưa thuê");

        rd_dathue.setText("Đã thuê");

        tb_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_table);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_clear.setText("Clear");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_sophong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nguoithue, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(lbl_tinhtrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_songuoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_sophong, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txt_diachi)
                                    .addComponent(txt_nguoithue))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_them)
                                    .addComponent(btn_clear)
                                    .addComponent(btn_thoat)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(rd_chuathue, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rd_dathue, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(cb_songuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sophong)
                    .addComponent(txt_sophong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_diachi)
                    .addComponent(txt_diachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clear))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nguoithue)
                    .addComponent(txt_nguoithue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_thoat))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tinhtrang)
                    .addComponent(rd_chuathue)
                    .addComponent(rd_dathue))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_songuoi)
                    .addComponent(cb_songuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        // TODO add your handling code here:
        txt_sophong.setText("");
        txt_diachi.setText("");
        txt_nguoithue.setText("");
        buttonGroup.clearSelection();
        cb_songuoi.setSelectedIndex(0);
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String str = txt_sophong.getText();
        String str1 = txt_diachi.getText();
        String str2 = txt_nguoithue.getText();
        if ("".equals(str)) {
            JOptionPane.showMessageDialog(this, "Không được để trống số phòng");
        } else if ("".equals(str1)) {
            JOptionPane.showMessageDialog(this, "Không được để trống địa chỉ");
        } else if ("".equals(str2)) {
            JOptionPane.showMessageDialog(this, "Không được để trống người thuê");
        } else {

            List<Phong> list = getList();
            Phong phong = new Phong();
            String soPhong = txt_sophong.getText();
            String diaChi = txt_diachi.getText();
            String nguoiThue = txt_nguoithue.getText();

            int soNguoi;
            soNguoi = Integer.parseInt((String) cb_songuoi.getSelectedItem());
            if (rd_chuathue.isSelected()) {
                phong.setTinhTrang(1);
            } else {
                phong.setTinhTrang(0);
            }

            phong.setSoNguoi(soNguoi);
            phong.setDiaChi(diaChi);
            phong.setNguoiThue(nguoiThue);
            phong.setSoPhong(soPhong);

            
            list.add(phong);
            addRow();
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void tb_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_tableMouseClicked
        // TODO add your handling code here:
        int row = tb_table.getSelectedRow();
        txt_sophong.setText((String) tb_table.getValueAt(row, 0).toString());
        txt_diachi.setText((String) tb_table.getValueAt(row, 1).toString());
        cb_songuoi.setSelectedItem(tb_table.getValueAt(row, 4).toString());
        txt_nguoithue.setText((String) tb_table.getValueAt(row, 2).toString());
        String trangThai = tb_table.getValueAt(row, 3).toString();
        if (tb_table.getValueAt(row, 3).toString().equals("Chưa thuê")) {
            rd_chuathue.setSelected(true);
        } else {
            rd_dathue.setSelected(true);
        }
        
    }//GEN-LAST:event_tb_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JComboBox<String> cb_songuoi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_diachi;
    private javax.swing.JLabel lbl_nguoithue;
    private javax.swing.JLabel lbl_songuoi;
    private javax.swing.JLabel lbl_sophong;
    private javax.swing.JLabel lbl_tinhtrang;
    private javax.swing.JRadioButton rd_chuathue;
    private javax.swing.JRadioButton rd_dathue;
    private javax.swing.JTable tb_table;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_nguoithue;
    private javax.swing.JTextField txt_sophong;
    // End of variables declaration//GEN-END:variables
}
