/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import entity.HoaDon;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.management.StringValueExp;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel dcbm;
    private DefaultTableModel dtm;
    List<HoaDon> listHoaDon = new ArrayList<>();

    public Main() {
        initComponents();
        addItemComboBox();
        addItemColumns();
        addRow();
        Thread t = new Thread(this);
        t.start();
    }

    public void addItemComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("Trẻ em");
        listItem.add("Người lớn");

        dcbm = (DefaultComboBoxModel) cb_loaive.getModel();
        for (String item : listItem) {
            dcbm.addElement(item);
        }
    }

    public void addItemColumns() {
        ArrayList<String> listItems = new ArrayList<>();
        listItems.add("Tên Khách Hàng");
        listItems.add("Loại Vé");
        listItems.add("Số Lượng");
        listItems.add("Thành Tiền");

        dtm = (DefaultTableModel) tb_kh.getModel();
        dtm.setColumnCount(0);
        for (String items : listItems) {
            dtm.addColumn(items);
        }
    }

    public void addRow() {
        dtm = (DefaultTableModel) tb_kh.getModel();
        dtm.setRowCount(0);
        for (HoaDon x : listHoaDon) {
            dtm.addRow(
                    new Object[]{
                        x.getTenKH(),
                        x.getLoaiVe(),
                        x.getSoLuong(),
                        x.getThanhTien()
                    }
            );
        }
    }
    
    public HoaDon timTheoTen(String ten){
        for (HoaDon hoaDon : listHoaDon) {
            if(hoaDon.getTenKH().equalsIgnoreCase(ten)){
                return hoaDon;
            }
        }
        return null;
    }
    
    public void findKhachHang(HoaDon hd){
        txt_tenkh.setText(hd.getTenKH());
        txt_soluong.setText(String.valueOf(hd.getSoLuong()));
        cb_loaive.setSelectedItem(hd.getLoaiVe());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_tenkh = new javax.swing.JLabel();
        txt_tenkh = new javax.swing.JTextField();
        lbl_loaive = new javax.swing.JLabel();
        cb_loaive = new javax.swing.JComboBox<>();
        lbl_soluong = new javax.swing.JLabel();
        txt_soluong = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_kh = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();
        btn_mo = new javax.swing.JButton();
        lbl_time = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_tenkh.setText("Tên Khách Hàng");

        lbl_loaive.setText("Loại vé");

        lbl_soluong.setText("Số Lượng");

        tb_kh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_kh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_khMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_kh);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_ghi.setText("Ghi File");

        btn_mo.setText("Mở File");
        btn_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moActionPerformed(evt);
            }
        });

        lbl_time.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_time.setForeground(new java.awt.Color(255, 0, 51));

        jButton1.setText("Find");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_loaive)
                                    .addComponent(lbl_soluong))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_tenkh)
                                    .addComponent(cb_loaive, 0, 168, Short.MAX_VALUE)
                                    .addComponent(txt_soluong))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_them, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_ghi, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_mo, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(87, 87, 87))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl_time, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tenkh)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_loaive)
                            .addComponent(cb_loaive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_xoa)))
                .addGap(19, 19, 19)
                .addComponent(btn_ghi)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_soluong)
                            .addComponent(txt_soluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_mo)))
                .addGap(12, 12, 12)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        if (txt_tenkh.getText().equals("") || txt_soluong.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống");
        } else {
            HoaDon hd = new HoaDon();
            String tenKH = txt_tenkh.getText();
            Object loaiVe = cb_loaive.getSelectedItem();
            int soLuong = Integer.parseInt(txt_soluong.getText());

            hd.setTenKH(tenKH);
            hd.setLoaiVe((String) loaiVe);
            hd.setSoLuong(soLuong);
            hd.setThanhTien(80000 * soLuong);
            listHoaDon.add(hd);
            addRow();

            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_moActionPerformed

    private void tb_khMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_khMouseClicked
        // TODO add your handling code here:
        int row = tb_kh.getSelectedRow();
        txt_tenkh.setText(tb_kh.getValueAt(row, 0).toString());
        cb_loaive.setSelectedItem(tb_kh.getValueAt(row, 1));
        txt_soluong.setText(tb_kh.getValueAt(row, 2).toString());
    }//GEN-LAST:event_tb_khMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int remove = tb_kh.getSelectedRow();
        listHoaDon.remove(remove);
        addRow();
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        findKhachHang(timTheoTen(txt_tenkh.getText()));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    @Override
    public void run() {
        while (true) {
            Calendar cal = Calendar.getInstance();
            int hour = cal.get(Calendar.HOUR_OF_DAY);
            int minute = cal.get(Calendar.MINUTE);
            int secord = cal.get(Calendar.SECOND);

            SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss aa");
            Date dat = cal.getTime();
            String time = sdf.format(dat);

            lbl_time.setText(time);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_mo;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_loaive;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_loaive;
    private javax.swing.JLabel lbl_soluong;
    private javax.swing.JLabel lbl_tenkh;
    private javax.swing.JLabel lbl_time;
    private javax.swing.JTable tb_kh;
    private javax.swing.JTextField txt_soluong;
    private javax.swing.JTextField txt_tenkh;
    // End of variables declaration//GEN-END:variables
}
