/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package on2;

import entity.PhieuMuon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    ButtonGroup buttonGroup = new ButtonGroup();
    private DefaultComboBoxModel defaultComboBoxModel;
    private DefaultTableModel defaultTableModel;
    List<PhieuMuon> listPhieuMuon = new ArrayList<>();

    public Main() {
        initComponents();
        rdGioiTinh();
        addItemComboBox();
        addItemColumns();
    }

    public void rdGioiTinh() {
        buttonGroup.add(rd_nam);
        buttonGroup.add(rd_nu);
    }

    public List<PhieuMuon> getList() {
        return listPhieuMuon;
    }

    private void addItemComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("Bộ môn 1");
        listItem.add("Bộ môn 2");

        defaultComboBoxModel = (DefaultComboBoxModel) cb_bomon.getModel();
        for (String item : listItem) {
            defaultComboBoxModel.addElement(item);
        }

    }

    public void addItemColumns() {
        ArrayList<String> listItems = new ArrayList<>();
        listItems.add("Tên sinh viên");
        listItems.add("Bộ môn");
        listItems.add("Giới tính");
        listItems.add("Tên sách");

        defaultTableModel = (DefaultTableModel) tb_sinhvien.getModel();
        defaultTableModel.setColumnCount(0);
        for (String listItem : listItems) {
            defaultTableModel.addColumn(listItem);
        }
    }

    public void addRow() {
        List<PhieuMuon> list = getList();
        defaultTableModel = (DefaultTableModel) tb_sinhvien.getModel();
        defaultTableModel.setRowCount(0);
        for (PhieuMuon x : list) {
            defaultTableModel.addRow(
                    new Object[]{
                        x.getTenSV(),
                        x.getBoMon(),
                        x.getGioiTinh(),
                        x.getTenSach()

                    }
            );
        }
    }

    private void ghiFile() throws FileNotFoundException, IOException {
        File file = new File("dataObject.txt");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {
            }
        }

        FileOutputStream fos = new FileOutputStream(file);
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        for (PhieuMuon phieuMuon : listPhieuMuon) {
            oos.writeObject(phieuMuon);
        }

        oos.close();
        fos.close();
    }

    private ArrayList<PhieuMuon> docFile() throws FileNotFoundException, IOException, ClassNotFoundException {
        File file = new File("dataObject.txt");
        if (!file.exists()) {
            try {
                file.createNewFile();
            } catch (IOException ex) {

            }
        }
        FileInputStream fis = new FileInputStream(file);
        ObjectInputStream ois = new ObjectInputStream(fis);

        PhieuMuon phieuMuon = new PhieuMuon();
        ArrayList<PhieuMuon> listPhieuMuon = new ArrayList<>();
        while (fis.available() > 0) {
            phieuMuon = (PhieuMuon) ois.readObject();
            listPhieuMuon.add(phieuMuon);

        }
        System.out.println(listPhieuMuon.size());

        ois.close();
        fis.close();

        return listPhieuMuon;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_tensv = new javax.swing.JLabel();
        lbl_bomon = new javax.swing.JLabel();
        lbl_gioitinh = new javax.swing.JLabel();
        lbl_tensach = new javax.swing.JLabel();
        lbl_timkiem = new javax.swing.JLabel();
        txt_tensv = new javax.swing.JTextField();
        cb_bomon = new javax.swing.JComboBox<>();
        rd_nam = new javax.swing.JRadioButton();
        rd_nu = new javax.swing.JRadioButton();
        txt_tensach = new javax.swing.JTextField();
        txt_timkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sinhvien = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_mo = new javax.swing.JButton();
        btn_loaddata = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_timkiem = new javax.swing.JButton();
        btn_ghi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Phiếu mượn sách");

        lbl_tensv.setText("Tên Sinh Viên");

        lbl_bomon.setText("Bộ môn");

        lbl_gioitinh.setText("Giới tính");

        lbl_tensach.setText("Tên Sách");

        lbl_timkiem.setText("Tìm kiếm");

        rd_nam.setText("Nam");

        rd_nu.setText("Nữ");

        txt_timkiem.setText("Nhập tên sinh viên");

        tb_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sinhvien);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_mo.setText("Mở file");
        btn_mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moActionPerformed(evt);
            }
        });

        btn_loaddata.setText("LoadData");
        btn_loaddata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loaddataActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_ghi.setText("Ghi file");
        btn_ghi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ghiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tensv)
                                    .addComponent(lbl_bomon)
                                    .addComponent(lbl_gioitinh)
                                    .addComponent(lbl_tensach)
                                    .addComponent(lbl_timkiem))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cb_bomon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btn_xoa))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(txt_timkiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                                .addComponent(txt_tensach, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(btn_mo, javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(btn_ghi, javax.swing.GroupLayout.Alignment.TRAILING)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(txt_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(136, 136, 136)
                                            .addComponent(btn_them)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(312, 312, 312)
                                        .addComponent(btn_timkiem))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rd_nam, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rd_nu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)
                                        .addComponent(btn_loaddata)))))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tensv)
                    .addComponent(txt_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them))
                .addGap(18, 18, 18)
                .addComponent(btn_timkiem)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_bomon)
                            .addComponent(cb_bomon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_gioitinh)
                            .addComponent(rd_nam)
                            .addComponent(rd_nu))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tensach)
                            .addComponent(txt_tensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_timkiem)
                            .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btn_xoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_loaddata)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ghi)
                        .addGap(18, 18, 18)
                        .addComponent(btn_mo)
                        .addGap(44, 44, 44)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sinhvienMouseClicked
        // TODO add your handling code here:
        int row = tb_sinhvien.getSelectedRow();
        txt_tensv.setText(tb_sinhvien.getValueAt(row, 0).toString());
        txt_tensach.setText(tb_sinhvien.getValueAt(row, 3).toString());
        cb_bomon.setSelectedItem(tb_sinhvien.getValueAt(row, 1));
        Object gioiTinh = tb_sinhvien.getValueAt(row, 2);
        if (tb_sinhvien.getValueAt(row, 2).toString().equals("Nam")) {
            rd_nam.setSelected(true);
        } else {
            rd_nu.setSelected(true);
        }
    }//GEN-LAST:event_tb_sinhvienMouseClicked

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String str = txt_tensv.getText();
        String str1 = txt_tensach.getText();
        if (str.equals("") || str1.equals("")) {
            JOptionPane.showMessageDialog(this, "Không được để trống.");
        } else {
            List<PhieuMuon> list = getList();
            PhieuMuon phieuMuon = new PhieuMuon();
            String tenSV = txt_tensv.getText();
            String tenSach = txt_tensach.getText();
            Object boMon = cb_bomon.getSelectedItem();
            if (rd_nam.isSelected()) {
                phieuMuon.setGioiTinh("Nam");
            } else {
                phieuMuon.setGioiTinh("Nữ");
            }

            phieuMuon.setTenSV(tenSV);
            phieuMuon.setTenSach(tenSach);
            phieuMuon.setBoMon((String) boMon);

            listPhieuMuon.add(phieuMuon);

            JOptionPane.showMessageDialog(this, "Thêm thành công.");
        }

    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int row = tb_sinhvien.getSelectedRow();
        listPhieuMuon.remove(row);
        try {
            ghiFile();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Xóa thành công.");
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_loaddataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loaddataActionPerformed
        try {
            // TODO add your handling code here:
            ArrayList<PhieuMuon> listPhieuMuon = docFile();
            defaultTableModel = (DefaultTableModel) tb_sinhvien.getModel();
            defaultTableModel.setRowCount(0);
            for (PhieuMuon x : listPhieuMuon) {
                defaultTableModel.addRow(
                        new Object[]{
                            x.getTenSV(),
                            x.getBoMon(),
                            x.getGioiTinh(),
                            x.getTenSach()

                        }
                );
            }

        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_loaddataActionPerformed

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        btn_timkiem = new JButton("Tìm kiếm");
        btn_timkiem.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String tenSV = JOptionPane.showInputDialog("Wat wil je zoeken?");
            }
        });
        add(btn_timkiem);
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_ghiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ghiActionPerformed
        // TODO add your handling code here:
        PhieuMuon pm = new PhieuMuon();
        pm.setTenSV(txt_tensv.getText().toString());
        pm.setTenSach(txt_tensach.getText().toString());
        listPhieuMuon.add(pm);
        try {
            ghiFile();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Ghi thành công.");

    }//GEN-LAST:event_btn_ghiActionPerformed

    private void btn_moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moActionPerformed
        try {
            // TODO add your handling code here:
            docFile();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_moActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ghi;
    private javax.swing.JButton btn_loaddata;
    private javax.swing.JButton btn_mo;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_bomon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_bomon;
    private javax.swing.JLabel lbl_gioitinh;
    private javax.swing.JLabel lbl_tensach;
    private javax.swing.JLabel lbl_tensv;
    private javax.swing.JLabel lbl_timkiem;
    private javax.swing.JRadioButton rd_nam;
    private javax.swing.JRadioButton rd_nu;
    private javax.swing.JTable tb_sinhvien;
    private javax.swing.JTextField txt_tensach;
    private javax.swing.JTextField txt_tensv;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
