/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onluyen;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultComboBoxModel defaultComboBoxModel;
    private DefaultTableModel defaultTableModel;
    List<SinhVien> listSinhVien = new ArrayList<>();

    public Main() {
        initComponents();
        addItemColumns();
        addItemComboBox();
        
        SinhVien sv1 = new SinhVien("Sv1", "Nguyen Van A", "UDPM", "Đang hoạt động");
        SinhVien sv2 = new SinhVien("Sv2", "Nguyen Van B", "UDPM", "Đang hoạt động");
        SinhVien sv3 = new SinhVien("Sv3", "Tran Thi C", "WEB", "Đang hoạt động");
        SinhVien sv4 = new SinhVien("Sv4", "Luu Thi D", "UDPM", "Đang hoạt động");
        
        listSinhVien.add(sv1);
        listSinhVien.add(sv2);
        listSinhVien.add(sv3);
        listSinhVien.add(sv4);
        
        addRow();
    }

    public List<SinhVien> getList() {
        return listSinhVien;
    }

    public void addItemComboBox() {
        ArrayList<String> listItem = new ArrayList<>();
        listItem.add("UDPM");
        listItem.add("WEB");

        defaultComboBoxModel = (DefaultComboBoxModel) cb_bomon.getModel();
        for (String item : listItem) {
            defaultComboBoxModel.addElement(item);
        }

        cb_bomon.setSelectedIndex(0);
    }

    public void addItemColumns() {
        ArrayList<String> listItems = new ArrayList<>();
        listItems.add("Mã sinh viên");
        listItems.add("Tên sinh viên");
        listItems.add("Bộ môn");
        listItems.add("Trạng thái");

        defaultTableModel = (DefaultTableModel) tb_sinhvien.getModel();
        defaultTableModel.setColumnCount(0);
        for (String listItem : listItems) {
            defaultTableModel.addColumn(listItem);
        }
    }

    public void addRow() {
        List<SinhVien> list = getList();
        defaultTableModel = (DefaultTableModel) tb_sinhvien.getModel();
        defaultTableModel.setRowCount(0);
        for (SinhVien sinhVien : list) {
            defaultTableModel.addRow(
                    new Object[]{
                        sinhVien.getMaSV(),
                        sinhVien.getTenSV(),
                        sinhVien.getBoMon(),
                        sinhVien.getTrangThai()
                    }
            );
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_masv = new javax.swing.JLabel();
        lbl_tensv = new javax.swing.JLabel();
        lbl_bomon = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        txt_tensv = new javax.swing.JTextField();
        cb_bomon = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_sinhvien = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        btn_write = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_masv.setText("Mã sinh viên");

        lbl_tensv.setText("Tên sinh viên");

        lbl_bomon.setText("Bộ môn");

        tb_sinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_sinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_sinhvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_sinhvien);

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_read.setText("Read");

        btn_write.setText("Write");
        btn_write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_writeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_masv)
                                .addGap(129, 129, 129)
                                .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_bomon)
                                .addGap(153, 153, 153)
                                .addComponent(cb_bomon, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114)
                                .addComponent(txt_tensv)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_them)
                            .addComponent(btn_xoa)
                            .addComponent(btn_read)
                            .addComponent(btn_write))
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_masv)
                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_them))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tensv)
                    .addComponent(txt_tensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa))
                .addGap(28, 28, 28)
                .addComponent(btn_read)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_bomon)
                    .addComponent(cb_bomon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(btn_write)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        // TODO add your handling code here:
        String str = txt_masv.getText();
        String str1 = txt_tensv.getText();
        if("".equals(str)){
            JOptionPane.showMessageDialog(this, "Không được để trống mã sv");
        } else if("".equals(str1)){
            JOptionPane.showMessageDialog(this, "Không được để trống tên sv");
        } else {
            List<SinhVien> list = getList();
            SinhVien sinhVien = new SinhVien();
            String maSV = txt_masv.getText();
            String tenSV = txt_tensv.getText();
            Object boMon = cb_bomon.getSelectedItem();
            
            sinhVien.setMaSV(maSV);
            sinhVien.setTenSV(tenSV);
            sinhVien.setBoMon((String) boMon);
            sinhVien.setTrangThai("Đang hoạt động");
            
            list.add(sinhVien);
            addRow();
            
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        int remove = tb_sinhvien.getSelectedRow();
        if(remove == -1){
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng để xóa");
        } else {
            int opt = JOptionPane.showConfirmDialog(null,"Bạn có muốn xóa ?","xóa",JOptionPane.YES_NO_CANCEL_OPTION);
            if(opt==0){
                int row = tb_sinhvien.getSelectedRow();
                listSinhVien.remove(row);
                addRow();
                JOptionPane.showMessageDialog(this, "Xóa thành công");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void tb_sinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_sinhvienMouseClicked
        // TODO add your handling code here:
        int row = tb_sinhvien.getSelectedRow();
        txt_masv.setText(tb_sinhvien.getValueAt(row, 0).toString());
        txt_tensv.setText(tb_sinhvien.getValueAt(row, 1).toString());
        cb_bomon.setSelectedItem(tb_sinhvien.getValueAt(row, 2));
    }//GEN-LAST:event_tb_sinhvienMouseClicked

    private void btn_writeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_writeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_writeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_write;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cb_bomon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_bomon;
    private javax.swing.JLabel lbl_masv;
    private javax.swing.JLabel lbl_tensv;
    private javax.swing.JTable tb_sinhvien;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_tensv;
    // End of variables declaration//GEN-END:variables
}
